### ISSUE TITLE
ReadMe file - How to build and run the example -> problem at point 3 in STM32 examples

### ISSUE THREAD

**Issue by trachubka** [niwciu/LCD_HD44780#33]
copy/paste instruction for STM32 examples at point 3 does not work

"cd ./LCD_HD44780/examples/STM32G071RB" -> folder STM32G071RB does not exist
"cd ./LCD_HD44780/examples/STM32G474RB" -> folder STM32G474RB does not exist

**Comment by niwciu** [comment]
Solved in v1.0.2 release
